version: '3.8'

services:
  frontend:
    image: node:20-alpine
    container_name: workout-management-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:4000/api
    command: sh -c "npm install && npm run dev"
    #command: sh -c "tail -f /dev/null"
    tty: true
    stdin_open: true

volumes:
  node_modules: